apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: ap-south-1

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 4
  iam:
    withAddonPolicies:
      albIngress: true
